<?php
function dutchtown_poll_init() {
	register_post_type( 'poll_response', array(
		'labels'                => array(
			'name'                  => __( 'Poll Responses', 'dutchtown' ),
			'singular_name'         => __( 'Poll Response', 'dutchtown' ),
			'all_items'             => __( 'All Poll Responses', 'dutchtown' ),
			'archives'              => __( 'Poll Response Archives', 'dutchtown' ),
			'attributes'            => __( 'Poll Respones Attributes', 'dutchtown' ),
			'insert_into_item'      => __( 'Insert into Poll Response', 'dutchtown' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Poll Response', 'dutchtown' ),
			'featured_image'        => _x( 'Featured Image', 'Poll', 'dutchtown' ),
			'set_featured_image'    => _x( 'Set featured image', 'Poll', 'dutchtown' ),
			'remove_featured_image' => _x( 'Remove featured image', 'Poll', 'dutchtown' ),
			'use_featured_image'    => _x( 'Use as featured image', 'Poll', 'dutchtown' ),
			'filter_items_list'     => __( 'Filter Poll Responses list', 'dutchtown' ),
			'items_list_navigation' => __( 'Poll Responses list navigation', 'dutchtown' ),
			'items_list'            => __( 'Poll Responses list', 'dutchtown' ),
			'new_item'              => __( 'New Poll Response', 'dutchtown' ),
			'add_new'               => __( 'Add New Response', 'dutchtown' ),
			'add_new_item'          => __( 'Add New Poll Response', 'dutchtown' ),
			'edit_item'             => __( 'Edit Poll Response', 'dutchtown' ),
			'view_item'             => __( 'View Poll Response', 'dutchtown' ),
			'view_items'            => __( 'View Poll Responses', 'dutchtown' ),
			'search_items'          => __( 'Search Poll Responses', 'dutchtown' ),
			'not_found'             => __( 'No Poll Responses found', 'dutchtown' ),
			'not_found_in_trash'    => __( 'No Poll Responses found in trash', 'dutchtown' ),
			'menu_name'             => __( 'Polls', 'dutchtown' ),
		),
		'public'                => true,
		'hierarchical'          => false,
		'show_ui'               => true,
		'show_in_nav_menus'     => true,
		'supports'              => array( 'title', 'custom-fields' ),
		'has_archive'           => false,
		'rewrite'               => false,
		'query_var'             => true,
		'menu_position'         => null,
		'menu_icon'             => 'dashicons-admin-post',
		'show_in_rest'          => true,
		'rest_base'             => 'Poll Response',
		'rest_controller_class' => 'WP_REST_Posts_Controller',
	) );
}
add_action( 'init', 'dutchtown_poll_init' );

function dutchtown_poll_category_init() {
	register_taxonomy( 'poll_category', array( 'poll_response' ), array(
		'hierarchical'      => false,
		'public'            => true,
		'show_in_nav_menus' => true,
		'show_ui'           => true,
		'show_admin_column' => true,
		'query_var'         => true,
		'rewrite'           => true,
		'capabilities'      => array(
			'manage_terms'  => 'edit_posts',
			'edit_terms'    => 'edit_posts',
			'delete_terms'  => 'edit_posts',
			'assign_terms'  => 'edit_posts',
		),
		'labels'            => array(
			'name'                       => __( 'Poll Categories', 'dutchtown' ),
			'singular_name'              => _x( 'Poll Category', 'taxonomy general name', 'dutchtown' ),
			'search_items'               => __( 'Search Poll Categories', 'dutchtown' ),
			'popular_items'              => __( 'Popular Poll Categories', 'dutchtown' ),
			'all_items'                  => __( 'All Poll Categories', 'dutchtown' ),
			'parent_item'                => __( 'Parent Poll Category', 'dutchtown' ),
			'parent_item_colon'          => __( 'Parent Poll Category:', 'dutchtown' ),
			'edit_item'                  => __( 'Edit Poll Category', 'dutchtown' ),
			'update_item'                => __( 'Update Poll Category', 'dutchtown' ),
			'view_item'                  => __( 'View Poll Category', 'dutchtown' ),
			'add_new_item'               => __( 'Add New Poll Category', 'dutchtown' ),
			'new_item_name'              => __( 'New Poll Category', 'dutchtown' ),
			'separate_items_with_commas' => __( 'Separate Poll Categories with commas', 'dutchtown' ),
			'add_or_remove_items'        => __( 'Add or remove Poll Categories', 'dutchtown' ),
			'choose_from_most_used'      => __( 'Choose from the most used Poll Categories', 'dutchtown' ),
			'not_found'                  => __( 'No Poll Categories found.', 'dutchtown' ),
			'no_terms'                   => __( 'No Poll Categories', 'dutchtown' ),
			'menu_name'                  => __( 'Poll Categories', 'dutchtown' ),
			'items_list_navigation'      => __( 'Poll Categories list navigation', 'dutchtown' ),
			'items_list'                 => __( 'Poll Categories list', 'dutchtown' ),
			'most_used'                  => _x( 'Most Used', 'poll_category', 'dutchtown' ),
			'back_to_items'              => __( '&larr; Back to Poll Categories', 'dutchtown' ),
		),
		'show_in_rest'      => true,
		'rest_base'         => 'poll_category',
		'rest_controller_class' => 'WP_REST_Terms_Controller',
	) );
}

add_action( 'init', 'dutchtown_poll_category_init' );