<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group( array(
        'key' => 'group_5fb66cf8a3c68',
        'title' => 'Poll Answers',
        'fields' => array(
            array(
                'key' => 'field_5fb66cffb0492',
                'label' => 'Add your own suggestions!',
                'name' => 'poll_answer',
                'type' => 'repeater',
                'instructions' => 'Enter your own suggestion below. Click "add another answer" if you\'d like to add up to three answers (40 character limit).',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 1,
                'max' => 3,
                'layout' => 'block',
                'button_label' => 'Add another answer',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5fb66e94bf00f',
                        'label' => '',
                        'name' => 'answer',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5fb66cffb0492',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_permissions' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 50,
                    ),
                ),
            ),
            array(
                'key' => 'field_5fcf7cf05a2cc',
                'label' => 'Decoy',
                'name' => 'poll_decoy',
                'type' => 'acfe_hidden',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'default_value' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'poll_response',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_permissions' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));

    acf_add_local_field_group( array(
        'key' => 'group_5fb95f9c3fd8e',
        'title' => 'Poll Block Fields',
        'fields' => array(
            array(
                'key' => 'field_5fb95fa4034b9',
                'label' => 'Poll Category',
                'name' => 'poll_category',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'taxonomy' => 'poll_category',
                'field_type' => 'select',
                'allow_null' => 0,
                'add_term' => 1,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'object',
                'acfe_bidirectional' => array(
                    'acfe_bidirectional_enabled' => '0',
                ),
                'multiple' => 0,
            ),
            array(
                'key' => 'field_5fbb075f32781',
                'label' => 'Poll Title',
                'name' => 'poll_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5fbb077232782',
                'label' => 'Poll Description',
                'name' => 'poll_description',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5fce3bee2e5d3',
                'label' => 'Poll Answers Allowed',
                'name' => 'poll_answers_allowed',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5fcf75b40e68d',
                'label' => 'Poll Result Style',
                'name' => 'poll_result_style',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'choices' => array(
                    'bar' => 'Bar',
                    'horizontalBar' => 'Horizontal Bar',
                    'line' => 'Line',
                    'pie' => 'Pie',
                    'doughnut' => 'Doughnut',
                ),
                'default_value' => 'bar',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5fd0c866130ec',
                'label' => 'Poll Result Max Results',
                'name' => 'poll_result_max_results',
                'type' => 'number',
                'instructions' => 'Number of results to show before items are sorted into "Other"',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_permissions' => '',
                'default_value' => 10,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => 20,
                'step' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/dutchtown-poll',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_permissions' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
endif;